spring.application.name=SkyGraph
spring.mongodb.uri=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@localhost:27017/SkyGraph?authSource=admin
# Se stai testando in locale
spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=password

logging.level.org.springframework.security=DEBUG
spring.security.user.password=password123







